version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: dbteste
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"

  app:
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - "8080"
    command: mvn clean install spring-boot:run
    depends_on:
      - postgres
